#!/usr/bin/env bash
# install-account-rotator-linux.sh
#
# Purpose : Install the Claude account-rotation daemon as a systemd --user service.
# Platform: Linux (Amazon Linux 2023 / Debian / Ubuntu — anything with systemd ≥ 232)
# Schedule: Always-on (KeepAlive equivalent). The daemon polls every 15 s internally.
# Rollback: systemctl --user disable --now claude-account-rotator.service
#           rm ~/.config/systemd/user/claude-account-rotator.service
#           systemctl --user daemon-reload
#
# Usage: bash install-account-rotator-linux.sh [--dry-run]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_NAME="claude-account-rotator"
UNIT_FILE="$HOME/.config/systemd/user/${SERVICE_NAME}.service"
DAEMON_SCRIPT="$SCRIPT_DIR/account-rotation/daemon.mjs"
LOG_FILE="$SCRIPT_DIR/account-rotation/rotation.log"
DRY_RUN=0

[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=1

log() { echo "[install-account-rotator] $*"; }
die() { echo "[install-account-rotator] ERROR: $*" >&2; exit 1; }

# ── Preflight ────────────────────────────────────────────────────────────────

command -v node >/dev/null 2>&1  || die "node not found (need Node 20+)"
command -v npx  >/dev/null 2>&1  || die "npx not found"
node --version | grep -qE 'v(2[0-9]|[3-9][0-9])' || die "Node 20+ required (got $(node --version))"
[[ -f "$DAEMON_SCRIPT" ]] || die "daemon.mjs not found at $DAEMON_SCRIPT"

# ── Dry-run validation ────────────────────────────────────────────────────────

log "Dry-run: testing daemon starts cleanly..."
TIMEOUT_EXIT=0
timeout 5 node "$DAEMON_SCRIPT" --status >/dev/null 2>&1 || TIMEOUT_EXIT=$?
# exit 1 = no pid file (expected on first run), anything else = real error
if [[ $TIMEOUT_EXIT -gt 1 && $TIMEOUT_EXIT -ne 124 ]]; then
  die "daemon.mjs --status exited $TIMEOUT_EXIT — fix errors before installing"
fi
log "Dry-run passed (exit $TIMEOUT_EXIT — ok)"

[[ $DRY_RUN -eq 1 ]] && { log "--dry-run: skipping install"; exit 0; }

# ── Write unit file ───────────────────────────────────────────────────────────

mkdir -p "$(dirname "$UNIT_FILE")"

cat > "$UNIT_FILE" <<EOF
# claude-account-rotator.service
# Generated by install-account-rotator-linux.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Purpose : Claude Max account rotation daemon — monitors usage and swaps
#           OAuth tokens automatically as 5-hour / 7-day caps approach.
# Platform: Linux (file-based vault in ~/.local/share/claude-rotation/)
# Rollback: systemctl --user disable --now claude-account-rotator.service

[Unit]
Description=Claude Max account rotation daemon
After=network.target

[Service]
Type=simple
ExecStart=$(command -v node) $DAEMON_SCRIPT
Restart=on-failure
RestartSec=30
# Give it 10 s to shut down cleanly before SIGKILL
TimeoutStopSec=10

# Logs
StandardOutput=append:${LOG_FILE}
StandardError=append:${LOG_FILE}

# Environment
Environment=HOME=$HOME
Environment=NODE_ENV=production
Environment=CLAUDE_ROTATOR_KEYCHAIN_ACCOUNT=${CLAUDE_ROTATOR_KEYCHAIN_ACCOUNT:-${USER:-ec2-user}}

[Install]
WantedBy=default.target
EOF

log "Unit file written: $UNIT_FILE"

# ── Enable & start ────────────────────────────────────────────────────────────

systemctl --user daemon-reload
systemctl --user enable  "$SERVICE_NAME"
systemctl --user restart "$SERVICE_NAME"

# ── Health check ─────────────────────────────────────────────────────────────

sleep 2
STATUS=$(systemctl --user is-active "$SERVICE_NAME" 2>&1)
if [[ "$STATUS" == "active" ]]; then
  log "READY — ${SERVICE_NAME}.service is active"
  systemctl --user status "$SERVICE_NAME" --no-pager -n 5
else
  echo ""
  log "NEEDS_FIXES — service status: $STATUS"
  systemctl --user status "$SERVICE_NAME" --no-pager -n 20
  echo ""
  log "Remediation: check logs with: journalctl --user -u ${SERVICE_NAME}.service -n 50"
  exit 1
fi
